apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
    JWT_SECRET: "{{ .Values.JwtSecret | b64enc }}"
    REDIS_PASSWORD: "{{ .Values.Redis.Password | b64enc }}"
