openapi: '3.0.3'
info:
  title: 'API Lock Service'
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: 'dev server'

components:
  schemas:
    Lock:
      type: object
      properties:
        id:
          type: string
          description: 'Идентификатор блокировки'
        timestamp:
          type: string
          format: date-time
          description: 'Время установки блокировки'
        username:
          type: string
          description: 'Пользователь, установивший блокировку'
  responses:
    InternalErrorResponse:
      description: 'Внутренняя ошибка'
      content:
        text/plain: {}
    UnauthorizedResponse:
      description: 'Неверный токен'
      content:
        text/plain: {}
  parameters:
    LockId:
      name: id
      in: path
      required: true
      description: 'Идентификатор блокировки'
      schema:
        type: string
  
  securitySchemes:
    JwtToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /locks:
    get:
      summary: 'Список блокировок'
      description: 'Возвращает список установленных блокировок'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lock'
        '500':
          $ref: "#/components/responses/InternalErrorResponse"
  /locks/{id}:
    get:
      summary: 'Информация о блокировке'
      description: 'Возвращает информацию об установленной блокировке (при ее наличии) или `410` если блокировка не установлена'
      parameters:
        - $ref: '#/components/parameters/LockId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lock'
        '410':
          description: 'Блокировка не установлена'
          content:
            text/plain: {}
        '500':
          $ref: '#/components/responses/InternalErrorResponse'
    put:
      summary: 'Установка блокировки'
      description: 'Устанавливает новую блокировку или обновляет существующую'
      parameters:
        - $ref: '#/components/parameters/LockId'
      security:
        - JwtToken: []
      responses:
        '204':
          description: 'Блокировка установлена/обновлена'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '500':
          $ref: '#/components/responses/InternalErrorResponse'
    delete:
      summary: 'Снятие блокировки'
      description: 'Удаляет блокировку'
      parameters:
        - $ref: '#/components/parameters/LockId'
      security:
        - JwtToken: []
      responses:
        '204':
          description: 'Блокировка снята'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '500':
          $ref: '#/components/responses/InternalErrorResponse'
